base.url=http://localhost:3000
base.url.admin=http://localhost:3001

admin.username=superadmin
admin.password=123456

# Browser: chrome, firefox, edge
browser=edge

# Timeout (giây)
implicit.wait.seconds=10
page.load.timeout.seconds=30
